app = "yunohost-fly"
primary_region = "sin"

kill_signal = "SIGINT"
kill_timeout = "120s"

[build]
  dockerfile = "Dockerfile"

[env]
  YUNOHOST_DOMAIN = "example.com"

[mounts]
  source = "yunodata"
  destination = "/var"

[[http_service]]
  internal_port = 80
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

[[vm]]
  memory = "2048"
  cpu_kind = "shared"
  cpus = 2
