app = "yunohost-fly"

primary_region = "sin"

kill_signal = "SIGINT"
kill_timeout = 120

[build]
  dockerfile = "Dockerfile"

[env]
  YUNOHOST_DOMAIN = "example.com"

[[mounts]]
  source = "yunodata"
  destination = "/var"

[[services]]
  internal_port = 80
  protocol = "tcp"

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "5s"
